### ISSUE TITLE
Licensing: migrate to detours 4

### ISSUE THREAD

**Issue by fredemmott** [microsoft/MSIX-PackageSupportFramework#193]
This project is being described as under the MIT license, but includes Detours 3.0 which is covered by a different EULA.

It's not clear if Microsoft are granting a 3.0 license with MSIX PSF; otherwise, using PSF in 64-bit applications may require a paid license, which appears to no longer be available from Microsoft.

The clearest way forward appears to be to migrate to Detours 4.0 which is MIT-licensed.

Migrating to 4.0 seems likely to be straightforward, given:

> Detours 4.0.1 is now open source under the MIT license. Detours is on GitHub at https://github.com/microsoft/detours. *The source code is identical to Build 343 of Detours 3.0*.  Detours Build 338 and later fix a security vulnerability that has been identified in releases of Detours before 3.0 Build 334.

from https://www.microsoft.com/en-us/research/project/detours/ - emphasis mine

**Comment by TimMangan** [comment]
I can't speak for Microsoft, but I was under the impression that the Detours 3 code was released via Github https://github.com/microsoft/Detours  under MIT license, and this project made a copy of that.   I also feel that the entire MSIX-PackageSupportFramework project was placed under an MIT license, even if they didn't update the file headers to express that.  But I'm not a lawyer.

The Detours Github has since moved on and, although most of that work is not needed, it would be important for this project to bring in those changes to stay up to date.

I'll keep this item open until I do that work in the TimMangan fork.  Microsoft does not appear to be maintaining their fork at this time.

**Comment by npuvvada** [comment]
The Detours version and license version used in this project is updated. 
Updating License terms, Readme and Version details of Detours

This is available from [PSF release : version 1.0.220926.1](https://github.com/microsoft/MSIX-PackageSupportFramework/releases/tag/1.0.220926.1)
